#!/bin/bash
# 读取当前版本号
VERSION=$(cat version.txt)
# 将版本号按"."分割成数组
IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
# 增加补丁版本号
PATCH=$((PATCH + 1))
# 新版本号
NEW_VERSION="$MAJOR.$MINOR.$PATCH"
# 保存新版本号到文件
echo $NEW_VERSION > version.txt
# 添加到 commit 中
git add version.txt
